# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/php:8.0

    working_directory: ~/repo

    steps:
      - run:
          command: sudo pear config-set php_ini /etc/php/8.0/cli/php.ini
          background: true
      - checkout
      - run: composer install -n --prefer-dist
      - run: sudo pecl install pcov xdebug
      - run:
          name: Check Syntax Error
          command: ./php-lint.sh
      - run: mkdir -p ~/reports/coverage
      - run: php -d pcov.enabled=1 ./vendor/bin/phpunit --coverage-html ~/reports/coverage tests/
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports